### ISSUE TITLE
There is an error.

### ISSUE THREAD

**Issue by tianshaokai** [rogerou/Baby#13]
javax.net.ssl.SSLHandshakeException: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate not valid until Wed Nov 06 05:36:50 GMT+08:00 2013 (compared to Thu Jan 01 10:34:39 GMT+08:00 1970

I can't login using my registered account. Would you help me? Can I add your qq account?

**Comment by rogerou** [comment]
@tianshaokai  there are two acconts in Baby , one is LeanCloud User Account,the other is Easemob Huanxin ChatService Account .  Hx Account username is not allowed to user Upper Alphabet ,so I have  some limits  in register Account . Hx Account and  the Leancloud account is the same ,but not  to use Upper Alphabet while registering a account .  
the code is here:
###    Pattern pattern = Pattern.compile("^[a-z0-9]+$");
        Matcher matcher = pattern.matcher(username);
        if (!matcher.matches()) {
            registerUser.setErrorEnabled(true);
            registerUser.setError("用户名不能有大写字母哦");
            return;
        }

**Comment by tianshaokai** [comment]
@rogerou  Thanks.

**Comment by rogerou** [comment]
@tianshaokai you're welcome :)
