### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by SmallLee** [rogerou/Baby#23]
对一个内容进行多次评论时，会出现评论内容显示重复的问题，之前的评论内容也看不到了

**Comment by rogerou** [comment]
@SmallLee  感谢你的反馈，最近这个问题我也注意到了，当初没到这样的情况，我会在这几天内修复。

**Comment by SmallLee** [comment]
嗯，应用做的很好，期待做的更完美

**Comment by rogerou** [comment]
@SmallLee Fix 修复了 你更新一下
