### ISSUE TITLE
Gradle refresh failed

### ISSUE THREAD

**Issue by huronghui** [rogerou/Baby#3]
您好，我在导入项目的时候，始终出现 “Gradle sync failed: Connection refused: connect”，想咨询一下，这是怎么回事？

**Comment by rogerou** [comment]
大概是因为网络的关系？因为这个项目里边很多库都是Compile的，如果不科学上网可能会比较慢，所以你需要科学上网 :https://github.com/XX-net/XX-Net

**Comment by rogerou** [comment]
@huronghui 还有你可以把Properties这个文件删掉再试试，因为我这里是有用到代理的。

**Comment by huronghui** [comment]
gradle 的问题是木有了，谢谢你了~但又出现一个新的问题，总是报 找不到v7 的3.0的包，我已经更改了项目的ToolVersion，还是会报这样的错误 Error:Could not find com.android.support:appcompat-v7:23.3.0.

**Comment by rogerou** [comment]
这个你试试更新sdk 我是用最新的 不行 你可以试着降低版本 找不到的话还是先确认你是否已经把sdk安装完毕
