### ISSUE TITLE
为什么有两个模块？

### ISSUE THREAD

**Issue by DanteAndroid** [rogerou/Baby#6]
EasyUI，app。新手还望指教

**Comment by DanteAndroid** [comment]
![image](https://cloud.githubusercontent.com/assets/10005563/15309224/7d2d1070-1c17-11e6-80cf-82a2c2aadf73.png)
另外运行报错麻烦您看看。

**Comment by rogerou** [comment]
@DanteAndroid  可以看看这个issue
https://github.com/rogerou/Baby/issues/4
easeUI我在README里边有详细说明，是环信的一个开源的聊天控件的包

**Comment by DanteAndroid** [comment]
必须要删除百度的so文件？那还怎么用地图功能。。

**Comment by rogerou** [comment]
这个警告无关重要根本不影响编译和运行，只是部分人强迫症看起来估计看起来比较难受。

**Comment by rogerou** [comment]
或者你可以试试最新版本的百度地图的sdk看看有没有问题。

**Comment by rogerou** [comment]
不过我以前试过更新到3.7还是有这个问题，然后就没深究，毕竟不影响运行和build但是就是看起来比较烦而已 ，在Google也找不过不少回答，也没有特别好的解决方法

**Comment by rogerou** [comment]
@DanteAndroid

**Comment by DanteAndroid** [comment]
谢谢，我在看您的代码。另外加您的qq没有回应。我是502273376

**Comment by rogerou** [comment]
最近比较忙
