### ISSUE TITLE
java.lang.NoClassDefFoundError: rx.subjects.SerializedSubject

### ISSUE THREAD

**Issue by qiuqiu3** [rogerou/Baby#7]
这个总是太头疼了，时好时坏的，昨天还行，今天就不行了。clean rebuild 删除build目录，所有方法都试了，就是不行。我的是开发环境 Android Studio 2.0 sdk 23 java8

**Comment by qiuqiu3** [comment]
自己找到了答案：
http://stackoverflow.com/a/34413765

**Comment by rogerou** [comment]
@qiuqiu3 超65K方法了吗。？

**Comment by rogerou** [comment]
我这里好像没这个问题，你可以贴一下详细的错误代码

**Comment by qiuqiu3** [comment]
下面这句报错，我用 stackoverflow 上面的方法解决了。
mSubject = new SerializedSubject<>(PublishSubject.create());

**Comment by rogerou** [comment]
@qiuqiu3 编译报错还是运行时报错？这句是rxbus里边的代码，这个是初始化Subject的代码。但是我看你的StackoverFlow是方法数的问题？

**Comment by qiuqiu3** [comment]
编译不报错，运行时报错。说来也奇怪解决了方法数的问题就解决了。

**Comment by rogerou** [comment]
@qiuqiu3 
我这里倒没出现过方法数的问题。。我感觉还达不到这个数的方法。我还以为是Rxbus Unscribe的时候忘记判空的错误 。

**Comment by rogerou** [comment]
问题我关闭了阿
