### ISSUE TITLE
整理到文章《源码提供！Android即时通讯和sns开源项目汇总》

### ISSUE THREAD

**Issue by CameloeAnthony** [rogerou/Baby#9]
已经把你这个项目整理到文章中。

源码提供！Android即时通讯和sns开源项目汇总

http://www.jianshu.com/p/b2ca52337fe5

帮你推广一下。 仔细看了你项目，写的很不错。很多地方值得借鉴。

**Comment by rogerou** [comment]
@CameloeAnthony 好的 十分欢迎哦 ：）
